version: '3'

services:

  # Generated documentation
  {{name}}-docs:
    image: swaggerapi/swagger-ui
    ports:
      - ${PORT_SWAGGER}:8080
    volumes:
      - ./docs/open-api:/usr/share/nginx/html/doc
    environment:
      URLS: "[
             { url: 'doc/{{open-api-file}}', name: '{{name}}'}
         ]"

  # Mock an API server using Prism (proxied via Nginx below)
  {{name}}-mock-server:
    image: stoplight/prism:4
    command: 'mock -d -h 0.0.0.0 /tmp/{{open-api-file}}'
    volumes:
      - ./docs/open-api/{{open-api-file}}:/tmp/{{open-api-file}}:ro

  # Nginx proxy server for the mock API so we can remove the content-type=json header which is being rejected when you access prism
  {{name}}-mock-proxy:
    image: nginx:latest
    volumes:
      - ./conf/nginx/nginx-mock.${ENV}.conf:/etc/nginx/conf.d/default.conf
    ports:
      - ${PORT_MOCK}:80

  # API nginx server
  {{name}}-api:
    image: nginx:alpine
    container_name: {{name}}-api
    volumes:
      - "./conf/nginx/nginx-api.${ENV}.conf:/etc/nginx/conf.d/default.conf"
      - "./src/php:/var/www/html"
      - "./data/logs/laravel:/var/www/html/storage/logs"
    ports:
      - "${PORT_API}:80"
    restart: always
    depends_on:
      - {{name}}-php
      - {{name}}-mysql

  # API PHP backend for Laravel
  {{name}}-php:
    image: nanoninja/php-fpm:latest
    container_name: {{name}}-php
    restart: always
    volumes:
      - "./conf/php/php.${ENV}.ini:/usr/local/etc/php/conf.d/php.ini"
      - "./src/php:/var/www/html"
      - "./docs/features:/var/www/html/features/api"

  {{name}}-mysql:
    image: mysql:8.0.21
    container_name: {{name}}-mysql
    restart: always
    env_file:
      - ".env"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "${PORT_MYSQL}:3306"
    volumes:
      - "./data/db/mysql:/var/lib/mysql"